package pizzerias;
// Generated 02/05/2021 17:41:00 by Hibernate Tools 4.3.1



/**
 * Detallepedido generated by hbm2java
 */
public class Detallepedido  implements java.io.Serializable {


     private int iddetallePedido;
     private Estadofactura estadofactura;
     private Factura factura;
     private Pedido pedido;
     private Pizza pizza;
     private int cantidad;
     private float precio;

    public Detallepedido() {
    }

    public Detallepedido(int iddetallePedido, Estadofactura estadofactura, Factura factura, Pedido pedido, Pizza pizza, int cantidad, float precio) {
       this.iddetallePedido = iddetallePedido;
       this.estadofactura = estadofactura;
       this.factura = factura;
       this.pedido = pedido;
       this.pizza = pizza;
       this.cantidad = cantidad;
       this.precio = precio;
    }
   
    public int getIddetallePedido() {
        return this.iddetallePedido;
    }
    
    public void setIddetallePedido(int iddetallePedido) {
        this.iddetallePedido = iddetallePedido;
    }
    public Estadofactura getEstadofactura() {
        return this.estadofactura;
    }
    
    public void setEstadofactura(Estadofactura estadofactura) {
        this.estadofactura = estadofactura;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Pizza getPizza() {
        return this.pizza;
    }
    
    public void setPizza(Pizza pizza) {
        this.pizza = pizza;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }




}


