package pizzerias;
// Generated 02/05/2021 17:41:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estadofactura generated by hbm2java
 */
public class Estadofactura  implements java.io.Serializable {


     private int idestadoFactura;
     private String nombre;
     private Set facturas = new HashSet(0);
     private Set detallepedidos = new HashSet(0);

    public Estadofactura() {
    }

	
    public Estadofactura(int idestadoFactura, String nombre) {
        this.idestadoFactura = idestadoFactura;
        this.nombre = nombre;
    }
    public Estadofactura(int idestadoFactura, String nombre, Set facturas, Set detallepedidos) {
       this.idestadoFactura = idestadoFactura;
       this.nombre = nombre;
       this.facturas = facturas;
       this.detallepedidos = detallepedidos;
    }
   
    public int getIdestadoFactura() {
        return this.idestadoFactura;
    }
    
    public void setIdestadoFactura(int idestadoFactura) {
        this.idestadoFactura = idestadoFactura;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getDetallepedidos() {
        return this.detallepedidos;
    }
    
    public void setDetallepedidos(Set detallepedidos) {
        this.detallepedidos = detallepedidos;
    }




}


