package pizzerias;
// Generated 02/05/2021 17:41:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int idfactura;
     private Estadofactura estadofactura;
     private Date fechaHoraEmision;
     private Set detallepedidos = new HashSet(0);
     private Set pedidos = new HashSet(0);

    public Factura() {
    }

	
    public Factura(int idfactura, Estadofactura estadofactura, Date fechaHoraEmision) {
        this.idfactura = idfactura;
        this.estadofactura = estadofactura;
        this.fechaHoraEmision = fechaHoraEmision;
    }
    public Factura(int idfactura, Estadofactura estadofactura, Date fechaHoraEmision, Set detallepedidos, Set pedidos) {
       this.idfactura = idfactura;
       this.estadofactura = estadofactura;
       this.fechaHoraEmision = fechaHoraEmision;
       this.detallepedidos = detallepedidos;
       this.pedidos = pedidos;
    }
   
    public int getIdfactura() {
        return this.idfactura;
    }
    
    public void setIdfactura(int idfactura) {
        this.idfactura = idfactura;
    }
    public Estadofactura getEstadofactura() {
        return this.estadofactura;
    }
    
    public void setEstadofactura(Estadofactura estadofactura) {
        this.estadofactura = estadofactura;
    }
    public Date getFechaHoraEmision() {
        return this.fechaHoraEmision;
    }
    
    public void setFechaHoraEmision(Date fechaHoraEmision) {
        this.fechaHoraEmision = fechaHoraEmision;
    }
    public Set getDetallepedidos() {
        return this.detallepedidos;
    }
    
    public void setDetallepedidos(Set detallepedidos) {
        this.detallepedidos = detallepedidos;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


