package pizzerias;
// Generated 02/05/2021 17:41:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pizza generated by hbm2java
 */
public class Pizza  implements java.io.Serializable {


     private int idpizza;
     private Tamanopizza tamanopizza;
     private Tipopizza tipopizza;
     private Variedadpizza variedadpizza;
     private String nombre;
     private float precio;
     private Set detallepedidos = new HashSet(0);

    public Pizza() {
    }

	
    public Pizza(int idpizza, Tamanopizza tamanopizza, Tipopizza tipopizza, Variedadpizza variedadpizza, String nombre, float precio) {
        this.idpizza = idpizza;
        this.tamanopizza = tamanopizza;
        this.tipopizza = tipopizza;
        this.variedadpizza = variedadpizza;
        this.nombre = nombre;
        this.precio = precio;
    }
    public Pizza(int idpizza, Tamanopizza tamanopizza, Tipopizza tipopizza, Variedadpizza variedadpizza, String nombre, float precio, Set detallepedidos) {
       this.idpizza = idpizza;
       this.tamanopizza = tamanopizza;
       this.tipopizza = tipopizza;
       this.variedadpizza = variedadpizza;
       this.nombre = nombre;
       this.precio = precio;
       this.detallepedidos = detallepedidos;
    }
   
    public int getIdpizza() {
        return this.idpizza;
    }
    
    public void setIdpizza(int idpizza) {
        this.idpizza = idpizza;
    }
    public Tamanopizza getTamanopizza() {
        return this.tamanopizza;
    }
    
    public void setTamanopizza(Tamanopizza tamanopizza) {
        this.tamanopizza = tamanopizza;
    }
    public Tipopizza getTipopizza() {
        return this.tipopizza;
    }
    
    public void setTipopizza(Tipopizza tipopizza) {
        this.tipopizza = tipopizza;
    }
    public Variedadpizza getVariedadpizza() {
        return this.variedadpizza;
    }
    
    public void setVariedadpizza(Variedadpizza variedadpizza) {
        this.variedadpizza = variedadpizza;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public Set getDetallepedidos() {
        return this.detallepedidos;
    }
    
    public void setDetallepedidos(Set detallepedidos) {
        this.detallepedidos = detallepedidos;
    }




}


