package pizzerias;
// Generated 02/05/2021 17:41:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipopizza generated by hbm2java
 */
public class Tipopizza  implements java.io.Serializable {


     private int idtipoPizza;
     private String nombre;
     private String descripcion;
     private Set pizzas = new HashSet(0);

    public Tipopizza() {
    }

	
    public Tipopizza(int idtipoPizza, String nombre, String descripcion) {
        this.idtipoPizza = idtipoPizza;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Tipopizza(int idtipoPizza, String nombre, String descripcion, Set pizzas) {
       this.idtipoPizza = idtipoPizza;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.pizzas = pizzas;
    }
   
    public int getIdtipoPizza() {
        return this.idtipoPizza;
    }
    
    public void setIdtipoPizza(int idtipoPizza) {
        this.idtipoPizza = idtipoPizza;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPizzas() {
        return this.pizzas;
    }
    
    public void setPizzas(Set pizzas) {
        this.pizzas = pizzas;
    }




}


