package pizzerias;
// Generated 02/05/2021 17:41:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Variedadpizza generated by hbm2java
 */
public class Variedadpizza  implements java.io.Serializable {


     private int idvariedadPizza;
     private String nombre;
     private String ingredientes;
     private Set pizzas = new HashSet(0);

    public Variedadpizza() {
    }

	
    public Variedadpizza(int idvariedadPizza, String nombre, String ingredientes) {
        this.idvariedadPizza = idvariedadPizza;
        this.nombre = nombre;
        this.ingredientes = ingredientes;
    }
    public Variedadpizza(int idvariedadPizza, String nombre, String ingredientes, Set pizzas) {
       this.idvariedadPizza = idvariedadPizza;
       this.nombre = nombre;
       this.ingredientes = ingredientes;
       this.pizzas = pizzas;
    }
   
    public int getIdvariedadPizza() {
        return this.idvariedadPizza;
    }
    
    public void setIdvariedadPizza(int idvariedadPizza) {
        this.idvariedadPizza = idvariedadPizza;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getIngredientes() {
        return this.ingredientes;
    }
    
    public void setIngredientes(String ingredientes) {
        this.ingredientes = ingredientes;
    }
    public Set getPizzas() {
        return this.pizzas;
    }
    
    public void setPizzas(Set pizzas) {
        this.pizzas = pizzas;
    }




}


